<?php

function getLangName ($lang)
{
    $all_langs = [
        'ace'         => ['name' => 'Achinese',                'native' => 'Aceh'],
        'af'          => ['name' => 'Afrikaans',               'native' => 'Afrikaans'],
        'agq'         => ['name' => 'Aghem',                   'native' => 'Aghem'],
        'ak'          => ['name' => 'Akan',                    'native' => 'Akan'],
        'an'          => ['name' => 'Aragonese',               'native' => 'aragonés'],
        'cch'         => ['name' => 'Atsam',                   'native' => 'Atsam'],
        'gn'          => ['name' => 'Guaraní',                 'native' => 'Avañe’ẽ'],
        'ae'          => ['name' => 'Avestan',                 'native' => 'avesta'],
        'ay'          => ['name' => 'Aymara',                  'native' => 'aymar aru'],
        'az'          => ['name' => 'Azerbaijani (Latin)',     'native' => 'azərbaycanca'],
        'id'          => ['name' => 'Indonesian',              'native' => 'Bahasa Indonesia'],
        'ms'          => ['name' => 'Malay',                   'native' => 'Bahasa Melayu'],
        'bm'          => ['name' => 'Bambara',                 'native' => 'bamanakan'],
        'jv'          => ['name' => 'Javanese (Latin)',        'native' => 'Basa Jawa'],
        'su'          => ['name' => 'Sundanese',               'native' => 'Basa Sunda'],
        'bh'          => ['name' => 'Bihari',                  'native' => 'Bihari'],
        'bi'          => ['name' => 'Bislama',                 'native' => 'Bislama'],
        'nb'          => ['name' => 'Norwegian Bokmål',        'native' => 'Bokmål'],
        'bs'          => ['name' => 'Bosnian',                 'native' => 'bosanski'],
        'br'          => ['name' => 'Breton',                  'native' => 'brezhoneg'],
        'ca'          => ['name' => 'Catalan',                 'native' => 'català'],
        'ch'          => ['name' => 'Chamorro',                'native' => 'Chamoru'],
        'ny'          => ['name' => 'Chewa',                   'native' => 'chiCheŵa'],
        'kde'         => ['name' => 'Makonde',                 'native' => 'Chimakonde'],
        'sn'          => ['name' => 'Shona',                   'native' => 'chiShona'],
        'co'          => ['name' => 'Corsican',                'native' => 'corsu'],
        'cy'          => ['name' => 'Welsh',                   'native' => 'Cymraeg'],
        'da'          => ['name' => 'Danish',                  'native' => 'dansk'],
        'se'          => ['name' => 'Northern Sami',           'native' => 'davvisámegiella'],
        'de'          => ['name' => 'German',                  'native' => 'Deutsch'],
        'luo'         => ['name' => 'Luo',                     'native' => 'Dholuo'],
        'nv'          => ['name' => 'Navajo',                  'native' => 'Diné bizaad'],
        'dua'         => ['name' => 'Duala',                   'native' => 'duálá'],
        'et'          => ['name' => 'Estonian',                'native' => 'eesti'],
        'na'          => ['name' => 'Nauru',                   'native' => 'Ekakairũ Naoero'],
        'guz'         => ['name' => 'Ekegusii',                'native' => 'Ekegusii'],
        'en'          => ['name' => 'English',                 'native' => 'English'],
        'en-AU'       => ['name' => 'Australian English',      'native' => 'Australian English'],
        'en-GB'       => ['name' => 'British English',         'native' => 'British English'],
        'en-CA'       => ['name' => 'Canadian English',        'native' => 'Canadian English'],
        'en-US'       => ['name' => 'U.S. English',            'native' => 'U.S. English'],
        'es'          => ['name' => 'Spanish',                 'native' => 'español'],
        'eo'          => ['name' => 'Esperanto',               'native' => 'esperanto'],
        'eu'          => ['name' => 'Basque',                  'native' => 'euskara'],
        'ewo'         => ['name' => 'Ewondo',                  'native' => 'ewondo'],
        'ee'          => ['name' => 'Ewe',                     'native' => 'eʋegbe'],
        'fil'         => ['name' => 'Filipino',                'native' => 'Filipino'],
        'fr'          => ['name' => 'French',                  'native' => 'français'],
        'fr-CA'       => ['name' => 'Canadian French',         'native' => 'français canadien'],
        'fy'          => ['name' => 'Western Frisian',         'native' => 'frysk'],
        'fur'         => ['name' => 'Friulian',                'native' => 'furlan'],
        'fo'          => ['name' => 'Faroese',                 'native' => 'føroyskt'],
        'gaa'         => ['name' => 'Ga',                      'native' => 'Ga'],
        'ga'          => ['name' => 'Irish',                   'native' => 'Gaeilge'],
        'gv'          => ['name' => 'Manx',                    'native' => 'Gaelg'],
        'sm'          => ['name' => 'Samoan',                  'native' => 'Gagana fa’a Sāmoa'],
        'gl'          => ['name' => 'Galician',                'native' => 'galego'],
        'ki'          => ['name' => 'Kikuyu',                  'native' => 'Gikuyu'],
        'gd'          => ['name' => 'Scottish Gaelic',         'native' => 'Gàidhlig'],
        'ha'          => ['name' => 'Hausa',                   'native' => 'Hausa'],
        'bez'         => ['name' => 'Bena',                    'native' => 'Hibena'],
        'ho'          => ['name' => 'Hiri Motu',               'native' => 'Hiri Motu'],
        'hr'          => ['name' => 'Croatian',                'native' => 'hrvatski'],
        'bem'         => ['name' => 'Bemba',                   'native' => 'Ichibemba'],
        'io'          => ['name' => 'Ido',                     'native' => 'Ido'],
        'ig'          => ['name' => 'Igbo',                    'native' => 'Igbo'],
        'rn'          => ['name' => 'Rundi',                   'native' => 'Ikirundi'],
        'ia'          => ['name' => 'Interlingua',             'native' => 'interlingua'],
        'iu-Latn'     => ['name' => 'Inuktitut (Latin)',       'native' => 'Inuktitut'],
        'sbp'         => ['name' => 'Sileibi',                 'native' => 'Ishisangu'],
        'nd'          => ['name' => 'North Ndebele',           'native' => 'isiNdebele'],
        'nr'          => ['name' => 'South Ndebele',           'native' => 'isiNdebele'],
        'xh'          => ['name' => 'Xhosa',                   'native' => 'isiXhosa'],
        'zu'          => ['name' => 'Zulu',                    'native' => 'isiZulu'],
        'it'          => ['name' => 'Italian',                 'native' => 'italiano'],
        'ik'          => ['name' => 'Inupiaq',                 'native' => 'Iñupiaq'],
        'dyo'         => ['name' => 'Jola-Fonyi',              'native' => 'joola'],
        'kea'         => ['name' => 'Kabuverdianu',            'native' => 'kabuverdianu'],
        'kaj'         => ['name' => 'Jju',                     'native' => 'Kaje'],
        'mh'          => ['name' => 'Marshallese',             'native' => 'Kajin M̧ajeļ'],
        'kl'          => ['name' => 'Kalaallisut',             'native' => 'kalaallisut'],
        'kln'         => ['name' => 'Kalenjin',                'native' => 'Kalenjin'],
        'kr'          => ['name' => 'Kanuri',                  'native' => 'Kanuri'],
        'kcg'         => ['name' => 'Tyap',                    'native' => 'Katab'],
        'kw'          => ['name' => 'Cornish',                 'native' => 'kernewek'],
        'naq'         => ['name' => 'Nama',                    'native' => 'Khoekhoegowab'],
        'rof'         => ['name' => 'Rombo',                   'native' => 'Kihorombo'],
        'kam'         => ['name' => 'Kamba',                   'native' => 'Kikamba'],
        'kg'          => ['name' => 'Kongo',                   'native' => 'Kikongo'],
        'jmc'         => ['name' => 'Machame',                 'native' => 'Kimachame'],
        'rw'          => ['name' => 'Kinyarwanda',             'native' => 'Kinyarwanda'],
        'asa'         => ['name' => 'Kipare',                  'native' => 'Kipare'],
        'rwk'         => ['name' => 'Rwa',                     'native' => 'Kiruwa'],
        'saq'         => ['name' => 'Samburu',                 'native' => 'Kisampur'],
        'ksb'         => ['name' => 'Shambala',                'native' => 'Kishambaa'],
        'swc'         => ['name' => 'Congo Swahili',           'native' => 'Kiswahili ya Kongo'],
        'sw'          => ['name' => 'Swahili',                 'native' => 'Kiswahili'],
        'dav'         => ['name' => 'Dawida',                  'native' => 'Kitaita'],
        'teo'         => ['name' => 'Teso',                    'native' => 'Kiteso'],
        'khq'         => ['name' => 'Koyra Chiini',            'native' => 'Koyra ciini'],
        'ses'         => ['name' => 'Songhay',                 'native' => 'Koyraboro senni'],
        'mfe'         => ['name' => 'Morisyen',                'native' => 'kreol morisien'],
        'ht'          => ['name' => 'Haitian',                 'native' => 'Kreyòl ayisyen'],
        'kj'          => ['name' => 'Kuanyama',                'native' => 'Kwanyama'],
        'ksh'         => ['name' => 'Kölsch',                  'native' => 'Kölsch'],
        'ebu'         => ['name' => 'Kiembu',                  'native' => 'Kĩembu'],
        'mer'         => ['name' => 'Kimîîru',                 'native' => 'Kĩmĩrũ'],
        'lag'         => ['name' => 'Langi',                   'native' => 'Kɨlaangi'],
        'lah'         => ['name' => 'Lahnda',                  'native' => 'Lahnda'],
        'la'          => ['name' => 'Latin',                   'native' => 'latine'],
        'lv'          => ['name' => 'Latvian',                 'native' => 'latviešu'],
        'to'          => ['name' => 'Tongan',                  'native' => 'lea fakatonga'],
        'lt'          => ['name' => 'Lithuanian',              'native' => 'lietuvių'],
        'li'          => ['name' => 'Limburgish',              'native' => 'Limburgs'],
        'ln'          => ['name' => 'Lingala',                 'native' => 'lingála'],
        'lg'          => ['name' => 'Ganda',                   'native' => 'Luganda'],
        'luy'         => ['name' => 'Oluluyia',                'native' => 'Luluhia'],
        'lb'          => ['name' => 'Luxembourgish',           'native' => 'Lëtzebuergesch'],
        'hu'          => ['name' => 'Hungarian',               'native' => 'magyar'],
        'mgh'         => ['name' => 'Makhuwa-Meetto',          'native' => 'Makua'],
        'mg'          => ['name' => 'Malagasy',                'native' => 'Malagasy'],
        'mt'          => ['name' => 'Maltese',                 'native' => 'Malti'],
        'mtr'         => ['name' => 'Mewari',                  'native' => 'Mewari'],
        'mua'         => ['name' => 'Mundang',                 'native' => 'Mundang'],
        'mi'          => ['name' => 'Māori',                   'native' => 'Māori'],
        'nl'          => ['name' => 'Dutch',                   'native' => 'Nederlands'],
        'nmg'         => ['name' => 'Kwasio',                  'native' => 'ngumba'],
        'yav'         => ['name' => 'Yangben',                 'native' => 'nuasue'],
        'nn'          => ['name' => 'Norwegian Nynorsk',       'native' => 'nynorsk'],
        'oc'          => ['name' => 'Occitan',                 'native' => 'occitan'],
        'ang'         => ['name' => 'Old English',             'native' => 'Old English'],
        'xog'         => ['name' => 'Soga',                    'native' => 'Olusoga'],
        'om'          => ['name' => 'Oromo',                   'native' => 'Oromoo'],
        'ng'          => ['name' => 'Ndonga',                  'native' => 'OshiNdonga'],
        'hz'          => ['name' => 'Herero',                  'native' => 'Otjiherero'],
        'uz-Latn'     => ['name' => 'Uzbek (Latin)',           'native' => 'oʼzbekcha'],
        'nds'         => ['name' => 'Low German',              'native' => 'Plattdüütsch'],
        'pl'          => ['name' => 'Polish',                  'native' => 'polski'],
        'pt'          => ['name' => 'Portuguese',              'native' => 'português'],
        'pt-BR'       => ['name' => 'Brazilian Portuguese',    'native' => 'português do Brasil'],
        'ff'          => ['name' => 'Fulah',                   'native' => 'Pulaar'],
        'pi'          => ['name' => 'Pahari-Potwari',          'native' => 'Pāli'],
        'aa'          => ['name' => 'Afar',                    'native' => 'Qafar'],
        'ty'          => ['name' => 'Tahitian',                'native' => 'Reo Māohi'],
        'ksf'         => ['name' => 'Bafia',                   'native' => 'rikpa'],
        'ro'          => ['name' => 'Romanian',                'native' => 'română'],
        'cgg'         => ['name' => 'Chiga',                   'native' => 'Rukiga'],
        'rm'          => ['name' => 'Romansh',                 'native' => 'rumantsch'],
        'qu'          => ['name' => 'Quechua',                 'native' => 'Runa Simi'],
        'nyn'         => ['name' => 'Nyankole',                'native' => 'Runyankore'],
        'ssy'         => ['name' => 'Saho',                    'native' => 'Saho'],
        'sc'          => ['name' => 'Sardinian',               'native' => 'sardu'],
        'de-CH'       => ['name' => 'Swiss High German',       'native' => 'Schweizer Hochdeutsch'],
        'gsw'         => ['name' => 'Swiss German',            'native' => 'Schwiizertüütsch'],
        'trv'         => ['name' => 'Taroko',                  'native' => 'Seediq'],
        'seh'         => ['name' => 'Sena',                    'native' => 'sena'],
        'nso'         => ['name' => 'Northern Sotho',          'native' => 'Sesotho sa Leboa'],
        'st'          => ['name' => 'Southern Sotho',          'native' => 'Sesotho'],
        'tn'          => ['name' => 'Tswana',                  'native' => 'Setswana'],
        'sq'          => ['name' => 'Albanian',                'native' => 'shqip'],
        'sid'         => ['name' => 'Sidamo',                  'native' => 'Sidaamu Afo'],
        'ss'          => ['name' => 'Swati',                   'native' => 'Siswati'],
        'sk'          => ['name' => 'Slovak',                  'native' => 'slovenčina'],
        'sl'          => ['name' => 'Slovene',                 'native' => 'slovenščina'],
        'so'          => ['name' => 'Somali',                  'native' => 'Soomaali'],
        'sr-Latn'     => ['name' => 'Serbian (Latin)',         'native' => 'Srpski'],
        'sh'          => ['name' => 'Serbo-Croatian',          'native' => 'srpskohrvatski'],
        'fi'          => ['name' => 'Finnish',                 'native' => 'suomi'],
        'sv'          => ['name' => 'Swedish',                 'native' => 'svenska'],
        'sg'          => ['name' => 'Sango',                   'native' => 'Sängö'],
        'tl'          => ['name' => 'Tagalog',                 'native' => 'Tagalog'],
        'tzm-Latn'    => ['name' => 'Central Atlas Tamazight (Latin)',  'native' => 'Tamazight'],
        'kab'         => ['name' => 'Kabyle',                  'native' => 'Taqbaylit'],
        'twq'         => ['name' => 'Tasawaq',                 'native' => 'Tasawaq senni'],
        'shi'         => ['name' => 'Tachelhit (Latin)',       'native' => 'Tashelhit'],
        'nus'         => ['name' => 'Nuer',                    'native' => 'Thok Nath'],
        'vi'          => ['name' => 'Vietnamese',              'native' => 'Tiếng Việt'],
        'tg-Latn'     => ['name' => 'Tajik (Latin)',           'native' => 'tojikī'],
        'lu'          => ['name' => 'Luba-Katanga',            'native' => 'Tshiluba'],
        've'          => ['name' => 'Venda',                   'native' => 'Tshivenḓa'],
        'tw'          => ['name' => 'Twi',                     'native' => 'Twi'],
        'tr'          => ['name' => 'Turkish',                 'native' => 'Türkçe'],
        'ale'         => ['name' => 'Aleut',                   'native' => 'Unangax tunuu'],
        'ca-valencia' => ['name' => 'Valencian',               'native' => 'valencià'],
        'vai-Latn'    => ['name' => 'Vai (Latin)',             'native' => 'Viyamíĩ'],
        'vo'          => ['name' => 'Volapük',                 'native' => 'Volapük'],
        'fj'          => ['name' => 'Fijian',                  'native' => 'vosa Vakaviti'],
        'wa'          => ['name' => 'Walloon',                 'native' => 'Walon'],
        'wae'         => ['name' => 'Walser',                  'native' => 'Walser'],
        'wen'         => ['name' => 'Sorbian',                 'native' => 'Wendic'],
        'wo'          => ['name' => 'Wolof',                   'native' => 'Wolof'],
        'ts'          => ['name' => 'Tsonga',                  'native' => 'Xitsonga'],
        'dje'         => ['name' => 'Zarma',                   'native' => 'Zarmaciine'],
        'yo'          => ['name' => 'Yoruba',                  'native' => 'Èdè Yorùbá'],
        'de-AT'       => ['name' => 'Austrian German',         'native' => 'Österreichisches Deutsch'],
        'is'          => ['name' => 'Icelandic',               'native' => 'íslenska'],
        'cs'          => ['name' => 'Czech',                   'native' => 'čeština'],
        'bas'         => ['name' => 'Basa',                    'native' => 'Ɓàsàa'],
        'mas'         => ['name' => 'Masai',                   'native' => 'ɔl-Maa'],
        'haw'         => ['name' => 'Hawaiian',                'native' => 'ʻŌlelo Hawaiʻi'],
        'el'          => ['name' => 'Greek',                   'native' => 'Ελληνικά'],
        'uz'          => ['name' => 'Uzbek (Cyrillic)',        'native' => 'Ўзбек'],
        'az-Cyrl'     => ['name' => 'Azerbaijani (Cyrillic)',  'native' => 'Азәрбајҹан'],
        'ab'          => ['name' => 'Abkhazian',               'native' => 'Аҧсуа'],
        'os'          => ['name' => 'Ossetic',                 'native' => 'Ирон'],
        'ky'          => ['name' => 'Kyrgyz',                  'native' => 'Кыргыз'],
        'sr'          => ['name' => 'Serbian (Cyrillic)',      'native' => 'Српски'],
        'av'          => ['name' => 'Avaric',                  'native' => 'авар мацӀ'],
        'ady'         => ['name' => 'Adyghe',                  'native' => 'адыгэбзэ'],
        'ba'          => ['name' => 'Bashkir',                 'native' => 'башҡорт теле'],
        'be'          => ['name' => 'Belarusian',              'native' => 'беларуская'],
        'bg'          => ['name' => 'Bulgarian',               'native' => 'български'],
        'kv'          => ['name' => 'Komi',                    'native' => 'коми кыв'],
        'mk'          => ['name' => 'Macedonian',              'native' => 'македонски'],
        'mn'          => ['name' => 'Mongolian (Cyrillic)',    'native' => 'монгол'],
        'ce'          => ['name' => 'Chechen',                 'native' => 'нохчийн мотт'],
        'ru'          => ['name' => 'Russian',                 'native' => 'русский'],
        'sah'         => ['name' => 'Yakut',                   'native' => 'саха тыла'],
        'tt'          => ['name' => 'Tatar',                   'native' => 'татар теле'],
        'tg'          => ['name' => 'Tajik (Cyrillic)',        'native' => 'тоҷикӣ'],
        'tk'          => ['name' => 'Turkmen',                 'native' => 'түркменче'],
        'uk'          => ['name' => 'Ukrainian',               'native' => 'українська'],
        'cv'          => ['name' => 'Chuvash',                 'native' => 'чӑваш чӗлхи'],
        'cu'          => ['name' => 'Church Slavic',           'native' => 'ѩзыкъ словѣньскъ'],
        'kk'          => ['name' => 'Kazakh',                  'native' => 'қазақ тілі'],
        'hy'          => ['name' => 'Armenian',                'native' => 'Հայերեն'],
        'yi'          => ['name' => 'Yiddish',                 'native' => 'ייִדיש'],
        'he'          => ['name' => 'Hebrew',                  'native' => 'עברית'],
        'ug'          => ['name' => 'Uyghur',                  'native' => 'ئۇيغۇرچە'],
        'ur'          => ['name' => 'Urdu',                    'native' => 'اردو'],
        'ar'          => ['name' => 'Arabic',                  'native' => 'العربية'],
        'uz-Arab'     => ['name' => 'Uzbek (Arabic)',          'native' => 'اۉزبېک'],
        'tg-Arab'     => ['name' => 'Tajik (Arabic)',          'native' => 'تاجیکی'],
        'sd'          => ['name' => 'Sindhi',                  'native' => 'سنڌي'],
        'fa'          => ['name' => 'Persian',                 'native' => 'فارسی'],
        'pa-Arab'     => ['name' => 'Punjabi (Arabic)',        'native' => 'پنجاب'],
        'ps'          => ['name' => 'Pashto',                  'native' => 'پښتو'],
        'ks'          => ['name' => 'Kashmiri (Arabic)',       'native' => 'کأشُر'],
        'ku'          => ['name' => 'Kurdish',                 'native' => 'کوردی'],
        'dv'          => ['name' => 'Divehi',                  'native' => 'ދިވެހިބަސް'],
        'ks-Deva'     => ['name' => 'Kashmiri (Devaganari)',   'native' => 'कॉशुर'],
        'kok'         => ['name' => 'Konkani',                 'native' => 'कोंकणी'],
        'doi'         => ['name' => 'Dogri',                   'native' => 'डोगरी'],
        'ne'          => ['name' => 'Nepali',                  'native' => 'नेपाली'],
        'pra'         => ['name' => 'Prakrit',                 'native' => 'प्राकृत'],
        'brx'         => ['name' => 'Bodo',                    'native' => 'बड़ो'],
        'bra'         => ['name' => 'Braj',                    'native' => 'ब्रज भाषा'],
        'mr'          => ['name' => 'Marathi',                 'native' => 'मराठी'],
        'mai'         => ['name' => 'Maithili',                'native' => 'मैथिली'],
        'raj'         => ['name' => 'Rajasthani',              'native' => 'राजस्थानी'],
        'sa'          => ['name' => 'Sanskrit',                'native' => 'संस्कृतम्'],
        'hi'          => ['name' => 'Hindi',                   'native' => 'हिन्दी'],
        'as'          => ['name' => 'Assamese',                'native' => 'অসমীয়া'],
        'bn'          => ['name' => 'Bengali',                 'native' => 'বাংলা'],
        'mni'         => ['name' => 'Manipuri',                'native' => 'মৈতৈ'],
        'pa'          => ['name' => 'Punjabi (Gurmukhi)',      'native' => 'ਪੰਜਾਬੀ'],
        'gu'          => ['name' => 'Gujarati',                'native' => 'ગુજરાતી'],
        'or'          => ['name' => 'Oriya',                   'native' => 'ଓଡ଼ିଆ'],
        'ta'          => ['name' => 'Tamil',                   'native' => 'தமிழ்'],
        'te'          => ['name' => 'Telugu',                  'native' => 'తెలుగు'],
        'kn'          => ['name' => 'Kannada',                 'native' => 'ಕನ್ನಡ'],
        'ml'          => ['name' => 'Malayalam',               'native' => 'മലയാളം'],
        'si'          => ['name' => 'Sinhala',                 'native' => 'සිංහල'],
        'th'          => ['name' => 'Thai',                    'native' => 'ไทย'],
        'lo'          => ['name' => 'Lao',                     'native' => 'ລາວ'],
        'bo'          => ['name' => 'Tibetan',                 'native' => 'པོད་སྐད་'],
        'dz'          => ['name' => 'Dzongkha',                'native' => 'རྫོང་ཁ'],
        'my'          => ['name' => 'Burmese',                 'native' => 'မြန်မာဘာသာ'],
        'ka'          => ['name' => 'Georgian',                'native' => 'ქართული'],
        'byn'         => ['name' => 'Blin',                    'native' => 'ብሊን'],
        'tig'         => ['name' => 'Tigre',                   'native' => 'ትግረ'],
        'ti'          => ['name' => 'Tigrinya',                'native' => 'ትግርኛ'],
        'am'          => ['name' => 'Amharic',                 'native' => 'አማርኛ'],
        'wal'         => ['name' => 'Wolaytta',                'native' => 'ወላይታቱ'],
        'chr'         => ['name' => 'Cherokee',                'native' => 'ᏣᎳᎩ'],
        'iu'          => ['name' => 'Inuktitut (Canadian Aboriginal Syllabics)',  'native' => 'ᐃᓄᒃᑎᑐᑦ'],
        'oj'          => ['name' => 'Ojibwa',                  'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ'],
        'cr'          => ['name' => 'Cree',                    'native' => 'ᓀᐦᐃᔭᐍᐏᐣ'],
        'km'          => ['name' => 'Khmer',                   'native' => 'ភាសាខ្មែរ'],
        'mn-Mong'     => ['name' => 'Mongolian (Mongolian)',   'native' => 'ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ'],
        'shi-Tfng'    => ['name' => 'Tachelhit (Tifinagh)',    'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ'],
        'tzm'         => ['name' => 'Central Atlas Tamazight (Tifinagh)', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ'],
        'yue'         => ['name' => 'Yue',                     'native' => '廣州話'],
        'ja'          => ['name' => 'Japanese',                'native' => '日本語'],
        'zh'          => ['name' => 'Chinese (Simplified)',    'native' => '简体中文'],
        'zh-Hant'     => ['name' => 'Chinese (Traditional)',   'native' => '繁體中文'],
        'ii'          => ['name' => 'Sichuan Yi',              'native' => 'ꆈꌠꉙ'],
        'vai'         => ['name' => 'Vai (Vai)',               'native' => 'ꕙꔤ'],
        'jv-Java'     => ['name' => 'Javanese (Javanese)',     'native' => 'ꦧꦱꦗꦮ'],
        'ko'          => ['name' => 'Korean',                  'native' => '한국어'],
        'no'          => ['name' => 'Norwegian',               'native' => 'Norsk'],
    ];

    return $all_langs[$lang]['native']  ?? $lang;
}
